### ISSUE TITLE
multiple of the same song

### ISSUE THREAD

**Issue by MidNoon** [briswells/prism-music#5]
fix it!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by briswells** [comment]
Working as designed

**Comment by MidNoon** [comment]
Still has this issue

**Comment by briswells** [comment]
Feel free to fork the prism music bot and add any desired features. Unfortunately our ironclad security policy stops us from recording the name of songs so there is no way to stop user from requesting the same ones.
